### PR TITLE
relax nokogiri dependency

### PR DESCRIPTION
**Pull request by bogdanRada**
Hello, I really need a newer version of nokogiri. The tests seem to pass. Can this be merged into master please and published to rubygems.org new release? Thank you very much

### CODE REVIEW

**Comment by softbrada** [comment]
@krishan , can we get this merged please? :) i really need this.

**Comment by bogdanRada** [comment]
@krishan , can we get this merged please? :) i really need this.

**Comment by krishan** [comment]
Sorry for the delay, I  unfortunately didn’t get notified about this until now. I’ll take a look at this tomorrow.

**Comment by krishan** [comment]
First off: Thank you very much for you contribution 👍 

I understand you would like to use a newer nokogiri with hyp_diff. But your PR would remove the dependency version constraint entirely, which is a violation of semantic versioning. This would put the applications using hyp_diff at risk of breakage, should nokogiri (or diff-lcs) release a version 2.0. Therefore I cannot merge the PR as-is.

But AFAICS this is also not necessary, since hypdiff is compatible with nokogiri in the newest version:
the latest nokogiri is 1.9 AFAICS and hyp_diff is compatible with that, see: https://github.com/krishan/hyp_diff/blob/e8c12497ef6bb53f355658aeadb70ac41e7e3818/hyp_diff.gemspec#L23

(`~> 1.6` means: anything above or equal to `1.6` but below `2.0`, so `1.9` is supported)

Could you tell me which version of nokogiri you are trying to use with hypdiff?

**Comment by bogdanRada** [comment]
@krishan , i updated the dependency. Please check. 
 
I don't know why for me it does not work as you describe. Maybe because i am using an older version of bundler 1.9.9 and i can't upgrade right now. But i need nokogiri to be bumped to latest version, and it works only if i change this dependency. 

I am opened to any suggestion.

**Comment by krishan** [comment]
FYI https://rubygems.org/gems/hyp_diff/versions/0.0.6

**Comment by bogdanRada** [comment]
Thank you very much

**Pull request merged**
